auth:
  method: simple
  users:
    alice:
      password: "5e884898da28047151d0e56f8dc6292773603d0d6aabbdd62a11ef721d1542d8" # sha256("password")
    bob:
      password: "8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918" # sha256("admin")

policies:
  alice:
    - dev
  bob:
    - dev
    - prod

environments:
  dev:
    redis:
      host: 127.0.0.1
      port: 6379
    nginx:
      host: 127.0.0.1
      port: 80
  prod:
    redis:
      host: 10.1.0.2
      port: 6379
